project:
  type: website

website:
  title: "demo"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: gallery.qmd
        text: Plot

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



